# Generated by Django 6.0.7 on 2026-07-17 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0002_remove_service_is_featured_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('completion_year', models.PositiveIntegerField(blank=True, null=True)),
                ('short_description', models.TextField(blank=True, help_text='A brief overview of the project.')),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('area', models.CharField(blank=True, help_text='For example: "1,200 sq ft".', max_length=100)),
                ('challenge', models.TextField(blank=True)),
                ('approach', models.TextField(blank=True)),
                ('result', models.TextField(blank=True)),
                ('materials', models.TextField(blank=True, help_text='Enter one material per line.')),
                ('is_featured', models.BooleanField(default=False, help_text='Featured projects receive the large case-study layout on the Projects page.')),
                ('featured_order', models.PositiveIntegerField(default=0, help_text='Controls the order of featured projects.')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Controls the order in the regular project gallery.')),
                ('is_published', models.BooleanField(default=False, help_text='Only published projects are visible on the website.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='services.servicecategory')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ('display_order', '-completion_year', 'title'),
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/images/')),
                ('alt_text', models.CharField(help_text='Briefly describe what is visible in the image for accessibility and search engines.', max_length=250)),
                ('caption', models.CharField(blank=True, max_length=250)),
                ('image_type', models.CharField(choices=[('before', 'Before'), ('after', 'After'), ('process', 'Process'), ('finished', 'Finished'), ('detail', 'Detail')], default='finished', max_length=20)),
                ('is_cover', models.BooleanField(default=False, help_text="Use this as the project's main image in the regular Projects gallery.")),
                ('show_on_homepage', models.BooleanField(default=False, help_text='Include this exact image in the homepage project gallery.')),
                ('homepage_order', models.PositiveIntegerField(default=0, help_text='Controls where this image appears on the homepage.')),
                ('homepage_size', models.CharField(choices=[('standard', 'Standard'), ('tall', 'Tall'), ('wide', 'Wide')], default='standard', help_text='Controls the size of this image in the homepage grid.', max_length=20)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Controls the image order within the project.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project Image',
                'verbose_name_plural': 'Project Images',
                'ordering': ('project', 'display_order', 'id'),
            },
        ),
    ]
