# Generated by Django 6.0.7 on 2026-07-17 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(help_text='Upload the highest-quality version available. The image will automatically be converted to WebP and limited to 1920 pixels on its longest edge.', upload_to='projects/images/'),
        ),
    ]
