# Generated by Django 6.0.7 on 2026-08-04 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projectimage_image'),
        ('services', '0002_remove_service_is_featured_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('display_order', '-completion_year', 'title')},
        ),
        migrations.AlterModelOptions(
            name='projectimage',
            options={'ordering': ('display_order', 'id')},
        ),
        migrations.RemoveField(
            model_name='project',
            name='featured_order',
        ),
        migrations.RemoveField(
            model_name='project',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='projectimage',
            name='homepage_order',
        ),
        migrations.RemoveField(
            model_name='projectimage',
            name='homepage_size',
        ),
        migrations.RemoveField(
            model_name='projectimage',
            name='image_type',
        ),
        migrations.RemoveField(
            model_name='projectimage',
            name='show_on_homepage',
        ),
        migrations.AddField(
            model_name='project',
            name='caption',
            field=models.TextField(blank=True, help_text='A short description shown beneath the project.'),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='role',
            field=models.CharField(choices=[('general', 'General'), ('before', 'Before'), ('after', 'After')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='services.servicecategory'),
        ),
        migrations.AlterField(
            model_name='project',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured projects appear as detailed case studies.'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='alt_text',
            field=models.CharField(help_text='Briefly describe what is visible in the image.', max_length=250),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(help_text='The image will automatically be converted to WebP and limited to 1920 pixels.', upload_to='projects/images/'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='is_cover',
            field=models.BooleanField(default=False, help_text="Use this as the project's main image."),
        ),
        migrations.AddConstraint(
            model_name='projectimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_cover', True)), fields=('project',), name='one_cover_image_per_project'),
        ),
        migrations.AddConstraint(
            model_name='projectimage',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'before')), fields=('project',), name='one_before_image_per_project'),
        ),
        migrations.AddConstraint(
            model_name='projectimage',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'after')), fields=('project',), name='one_after_image_per_project'),
        ),
    ]
