# Generated by Django 6.0.7 on 2026-08-05 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_options_alter_projectimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='homepage_size',
            field=models.CharField(choices=[('standard', 'Standard'), ('tall', 'Tall'), ('wide', 'Wide')], default='standard', help_text="Controls this featured project's card size on the homepage.", max_length=10),
        ),
    ]
