# Generated by Django 6.0.7 on 2026-08-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_homepage_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='is_cover',
            field=models.BooleanField(default=False, help_text="Use this as the project's main image. If none is selected for a project, then the first in display order is used as the cover."),
        ),
    ]
