# Generated by Django 6.0.7 on 2026-08-09 06:25

import django.core.validators
import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_projectimage_is_cover'),
        ('services', '0002_remove_service_is_featured_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='completion_year',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), projects.models.validate_completion_year]),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='is_cover',
            field=models.BooleanField(default=False, help_text="Use this as the project's main image. If none is selected for a project, the first in display order is used."),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(('completion_year__isnull', True), ('completion_year__gte', 1900), _connector='OR'), name='project_completion_year_at_least_1900'),
        ),
    ]
