# Generated by Django 6.0.7 on 2026-08-05 20:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=110, unique=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Job Category',
                'verbose_name_plural': 'Job Categories',
                'ordering': ('display_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=170, unique=True)),
                ('location', models.CharField(max_length=150)),
                ('seniority', models.CharField(blank=True, choices=[('entry', 'Entry Level'), ('mid-level', 'Mid-Level'), ('senior', 'Senior'), ('lead', 'Lead'), ('manager', 'Manager')], help_text='Leave blank when a seniority badge does not apply.', max_length=20)),
                ('employment_type', models.CharField(choices=[('full-time', 'Full-Time'), ('part-time', 'Part-Time'), ('seasonal', 'Seasonal'), ('temporary', 'Temporary'), ('contract', 'Contract'), ('internship', 'Internship')], max_length=20)),
                ('is_urgent', models.BooleanField(default=False)),
                ('posted_at', models.DateField(default=django.utils.timezone.localdate)),
                ('pay_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('pay_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('pay_unit', models.CharField(choices=[('hour', 'Per Hour'), ('day', 'Per Day'), ('week', 'Per Week'), ('year', 'Per Year'), ('project', 'Per Project')], default='hour', max_length=20)),
                ('description', models.TextField(max_length=5000)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_postings', to='careers.jobcategory')),
            ],
            options={
                'verbose_name': 'Job Posting',
                'verbose_name_plural': 'Job Postings',
                'ordering': ('display_order', '-posted_at', 'title'),
            },
        ),
        migrations.CreateModel(
            name='JobNiceToHave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nice_to_haves', to='careers.jobposting')),
            ],
            options={
                'verbose_name': 'Job Nice to Have',
                'verbose_name_plural': 'Job Nice to Haves',
                'ordering': ('display_order', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='JobRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='careers.jobposting')),
            ],
            options={
                'verbose_name': 'Job Requirement',
                'verbose_name_plural': 'Job Requirements',
                'ordering': ('display_order', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='JobResponsibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsibilities', to='careers.jobposting')),
            ],
            options={
                'verbose_name': 'Job Responsibility',
                'verbose_name_plural': 'Job Responsibilities',
                'ordering': ('display_order', 'pk'),
            },
        ),
        migrations.AddConstraint(
            model_name='jobposting',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('pay_min__isnull', True), ('pay_max__isnull', True)), models.Q(('pay_min__isnull', False), ('pay_max__isnull', False), ('pay_min__gte', 0), ('pay_max__gte', models.F('pay_min'))), _connector='OR'), name='careers_job_valid_pay_range'),
        ),
    ]
