# Generated by Django 6.0.7 on 2026-08-05 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=220, unique=True),
        ),
    ]
