# Generated by Django 6.0.7 on 2026-08-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_alter_jobposting_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobposting',
            options={'ordering': ('display_order', '-posted_at', 'title', 'pk'), 'verbose_name': 'Job Posting', 'verbose_name_plural': 'Job Postings'},
        ),
        migrations.AlterField(
            model_name='jobcategory',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=110, unique=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=170, unique=True),
        ),
        migrations.AddConstraint(
            model_name='jobcategory',
            constraint=models.CheckConstraint(condition=models.Q(('slug', ''), _negated=True), name='careers_cat_slug_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='jobposting',
            constraint=models.CheckConstraint(condition=models.Q(('slug', ''), _negated=True), name='careers_job_slug_not_empty'),
        ),
    ]
