# Generated by Django 6.0.7 on 2026-07-16 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Service Category',
                'verbose_name_plural': 'Service Categories',
                'ordering': ('display_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('subtitle', models.CharField(max_length=200)),
                ('overview', models.TextField(help_text='The primary description of the service.')),
                ('process_description', models.TextField(help_text='Additional information about the installation process, materials, guarantees, or customer experience.')),
                ('primary_image', models.ImageField(upload_to='services/images/primary/')),
                ('primary_image_alt', models.CharField(help_text='Describe the primary image for accessibility and search engines.', max_length=200)),
                ('supporting_image_one', models.ImageField(upload_to='services/images/supporting/')),
                ('supporting_image_one_alt', models.CharField(help_text='Describe the first supporting image for accessibility and search engines.', max_length=200)),
                ('supporting_image_two', models.ImageField(upload_to='services/images/supporting/')),
                ('supporting_image_two_alt', models.CharField(help_text='Describe the second supporting image for accessibility and search engines.', max_length=200)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False, help_text='Display this service in featured service lists.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive services are hidden from the public website.')),
                ('seo_title', models.CharField(blank=True, help_text='Optional search-engine title. Leave blank to use the service name.', max_length=60)),
                ('seo_description', models.CharField(blank=True, help_text='Optional search-engine description for this service.', max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='services.servicecategory')),
            ],
            options={
                'ordering': ('display_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ServiceIncludedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='included_items', to='services.service')),
            ],
            options={
                'verbose_name': 'Included Item',
                'verbose_name_plural': 'Included Items',
                'ordering': ('display_order', 'id'),
            },
        ),
    ]
