# Generated by Django 6.0.7 on 2026-07-16 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='service',
            name='seo_description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='seo_title',
        ),
    ]
