# Generated by Django 6.0.7 on 2026-08-05 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('service_type', models.CharField(help_text="The submitted service slug, or a special value such as 'multiple-services' or 'not-sure'.", max_length=150)),
                ('project_size', models.CharField(choices=[('not-sure', 'Not sure'), ('small', 'Small — under 500 sq ft'), ('medium', 'Medium — 500–1,500 sq ft'), ('large', 'Large — 1,500–3,000 sq ft'), ('xl', 'XL / Commercial — 3,000+ sq ft')], default='not-sure', max_length=20)),
                ('budget', models.CharField(choices=[('Not sure', 'Not sure'), ('<$5k', 'Under $5,000'), ('$5–15k', '$5,000–$15,000'), ('$15–30k', '$15,000–$30,000'), ('$30–60k', '$30,000–$60,000'), ('$60k+', '$60,000+')], default='Not sure', max_length=20)),
                ('timeline', models.CharField(blank=True, choices=[('ASAP', 'ASAP'), ('Within 1 month', 'Within 1 month'), ('1–3 months', '1–3 months'), ('3–6 months', '3–6 months'), ('This year', 'This year'), ('Just planning', 'Just planning'), ('Not sure yet', 'Not sure yet')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('heard_about', models.CharField(blank=True, choices=[('Google Search', 'Google Search'), ('Houzz', 'Houzz'), ('Neighbour / Word of Mouth', 'Neighbour / Word of Mouth'), ('Facebook / Instagram', 'Facebook / Instagram'), ('Saw our yard sign', 'Saw our yard sign'), ('Returning customer', 'Returning customer'), ("Not sure / don't remember", "Not sure / don't remember"), ('Other', 'Other')], max_length=50)),
                ('consent', models.BooleanField(default=False, help_text='Whether the customer agreed to be contacted.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Quote Request',
                'verbose_name_plural': 'Quote Requests',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='QuoteRequestPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='quote-requests/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quote_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='contact.quoterequest')),
            ],
            options={
                'verbose_name': 'Quote Request Photo',
                'verbose_name_plural': 'Quote Request Photos',
                'ordering': ('created_at',),
            },
        ),
    ]
