# Generated by Django 6.0.7 on 2026-08-05 20:27

import contact.models
import contact.storage
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
        ('contact', '0002_quoterequest_quoterequestphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsubmission',
            name='message',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='description',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='quoterequestphoto',
            name='image',
            field=models.FileField(storage=contact.storage.PrivateMediaStorage(), upload_to='quote-requests/%Y/%m/'),
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('years_experience', models.CharField(choices=[('under-1', 'Less than 1 year'), ('1-3', '1–3 years'), ('4-6', '4–6 years'), ('7-10', '7–10 years'), ('10-plus', '10+ years')], max_length=20)),
                ('availability', models.CharField(choices=[('immediately', 'Immediately'), ('within-1-week', 'Within 1 week'), ('within-2-weeks', 'Within 2 weeks'), ('within-1-month', 'Within 1 month'), ('over-1-month', 'More than 1 month'), ('flexible', 'Flexible')], max_length=30)),
                ('pay_range_response', models.CharField(choices=[('accept', 'Yes, this works for me'), ('discuss', "I'd like to discuss")], max_length=20)),
                ('motivation', models.TextField(max_length=5000, validators=[django.core.validators.MinLengthValidator(20)], verbose_name="Why do you want to work at Grayson's?")),
                ('resume', models.FileField(blank=True, storage=contact.storage.PrivateMediaStorage(), upload_to='job-applications/resumes/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('pdf', 'doc', 'docx')), contact.models.validate_resume_size, contact.models.validate_resume_contents])),
                ('consent', models.BooleanField(default=False, help_text="The applicant agreed that Grayson's Services may review their information for this and future openings.", validators=[contact.models.validate_consent_is_accepted])),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('interview', 'Interview'), ('offer', 'Offer'), ('hired', 'Hired'), ('not-selected', 'Not Selected'), ('withdrawn', 'Withdrawn')], default='new', max_length=20)),
                ('internal_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='careers.jobposting')),
            ],
            options={
                'verbose_name': 'Job Application',
                'verbose_name_plural': 'Job Applications',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['job_posting', 'status'], name='contact_job_job_pos_196377_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('consent', True)), name='contact_job_application_requires_consent')],
            },
        ),
    ]
