# Generated by Django 6.0.7 on 2026-08-10 20:31

import contact.storage
import contact.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_contactsubmission_message_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactsubmission',
            options={'ordering': ('-created_at', '-pk'), 'verbose_name': 'Contact Submission', 'verbose_name_plural': 'Contact Submissions'},
        ),
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'ordering': ('-created_at', '-pk'), 'verbose_name': 'Job Application', 'verbose_name_plural': 'Job Applications'},
        ),
        migrations.AlterModelOptions(
            name='quoterequest',
            options={'ordering': ('-created_at', '-pk'), 'verbose_name': 'Quote Request', 'verbose_name_plural': 'Quote Requests'},
        ),
        migrations.AlterModelOptions(
            name='quoterequestphoto',
            options={'ordering': ('created_at', 'pk'), 'verbose_name': 'Quote Request Photo', 'verbose_name_plural': 'Quote Request Photos'},
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='subject',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='service_type',
            field=models.CharField(help_text="The submitted active service slug, 'multiple-services', or 'not-sure'. The stored value remains a historical snapshot.", max_length=150),
        ),
        migrations.AlterField(
            model_name='quoterequestphoto',
            name='image',
            field=models.FileField(storage=contact.storage.PrivateMediaStorage(), upload_to='quote-requests/%Y/%m/', validators=[contact.validators.validate_quote_photo]),
        ),
        migrations.AddConstraint(
            model_name='quoterequest',
            constraint=models.CheckConstraint(condition=models.Q(('consent', True)), name='contact_quote_request_requires_consent'),
        ),
    ]
