# Generated by Django 6.0.7 on 2026-07-17 22:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_alter_projectimage_image'),
        ('services', '0002_remove_service_is_featured_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=150)),
                ('role', models.CharField(blank=True, help_text='For example: "Homeowners" or "Homeowners · Bloomington, IN".', max_length=150)),
                ('quote', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='Rating from 1 to 5 stars.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('source', models.CharField(choices=[('google', 'Google'), ('facebook', 'Facebook'), ('in_person', 'In Person')], default='google', max_length=20)),
                ('profile_image', models.ImageField(blank=True, help_text='Optional. Initials can be displayed when no image is provided.', null=True, upload_to='reviews/profile-images/')),
                ('review_month', models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('review_year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2015)])),
                ('is_featured', models.BooleanField(default=False, help_text='Featured reviews receive the large presentation on the homepage. Max 2 Recommended.')),
                ('featured_order', models.PositiveIntegerField(default=0, help_text='Controls the order of featured reviews.')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Controls the order on the complete Reviews page.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive reviews are hidden from the website.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='Optional. Leave blank for a general review. When a project is selected, its category is used automatically.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='services.servicecategory')),
                ('project', models.ForeignKey(blank=True, help_text='Optionally connect this review to a completed project.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='projects.project')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ('display_order', '-review_year', '-review_month', 'reviewer_name'),
            },
        ),
    ]
