# Generated by Django 6.0.7 on 2026-07-17 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Optional. The image will automatically be converted to WebP and limited to 512 pixels on its longest edge. Initials will be displayed when no image is provided.', null=True, upload_to='reviews/profile-images/'),
        ),
    ]
