# Generated by Django 6.0.7 on 2026-07-17 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projectimage_image'),
        ('reviews', '0002_alter_review_profile_image'),
        ('services', '0002_remove_service_is_featured_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='featured_order',
        ),
        migrations.AddField(
            model_name='review',
            name='homepage_order',
            field=models.PositiveIntegerField(default=0, help_text="Controls this review's position on the homepage. Only applies when homepage display is enabled."),
        ),
        migrations.AddField(
            model_name='review',
            name='show_on_homepage',
            field=models.BooleanField(default=False, help_text='Select this review for display on the homepage. This can be enabled for regular or featured reviews.'),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured reviews use the large review presentation. They must be connected to a project. A maximum of two featured homepage reviews is recommended.'),
        ),
        migrations.AlterField(
            model_name='review',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Optional for regular reviews. Required for featured reviews.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='projects.project'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('is_featured', False), ('project__isnull', False), _connector='OR'), name='featured_review_requires_project'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='review_rating_between_1_and_5'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('review_month__gte', 1), ('review_month__lte', 12)), name='review_month_between_1_and_12'),
        ),
    ]
