# Generated by Django 6.0.7 on 2026-08-09 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_projectimage_is_cover'),
        ('reviews', '0003_remove_review_featured_order_review_homepage_order_and_more'),
        ('services', '0002_remove_service_is_featured_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('review_year__gte', 2015)), name='review_year_at_least_2015'),
        ),
    ]
