# Generated by Django 6.0.7 on 2026-07-12 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default="Grayson's Services", max_length=150)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('logo', models.ImageField(blank=True, help_text='Upload a high-quality PNG or WebP image.', null=True, upload_to='site/branding/')),
                ('favicon', models.ImageField(blank=True, help_text='Upload a square PNG or WebP image.', null=True, upload_to='site/branding/')),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address_line_1', models.CharField(blank=True, max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('service_area', models.CharField(blank=True, help_text='Example: Bloomington and surrounding communities.', max_length=255)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('google_business_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('seo_title', models.CharField(blank=True, help_text='Used as the default page title.', max_length=70)),
                ('seo_description', models.CharField(blank=True, help_text='Used as the default search description.', max_length=170)),
                ('social_image', models.ImageField(blank=True, help_text='Recommended dimensions: 1200 × 630 pixels.', null=True, upload_to='site/seo/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
    ]
