# Generated by Django 6.0.7 on 2026-07-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_businesshours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesshours',
            name='closing_time',
            field=models.TimeField(blank=True, help_text='Example: 5:00 PM or 17:00.', null=True),
        ),
        migrations.AlterField(
            model_name='businesshours',
            name='opening_time',
            field=models.TimeField(blank=True, help_text='Example: 8:00 AM or 08:00.', null=True),
        ),
    ]
