# Generated by Django 6.0.7 on 2026-07-12 18:59

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_businesshours_closing_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload a PNG, JPEG, or WebP logo no larger than 2 MB. Horizontal, square, and vertical logos are supported. For best performance, use an image around 1000 pixels on its longest side and under 200 KB.', null=True, upload_to='site/branding/', validators=[core.validators.validate_logo]),
        ),
    ]
