# Generated by Django 6.0.7 on 2026-07-12 19:10

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_sitesettings_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='optimized_logo',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='site/branding/optimized/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload a PNG, JPEG, or WebP logo no larger than 2 MB. Horizontal, square, and vertical logos are supported. An optimized website copy will be created automatically.', null=True, upload_to='site/branding/originals/', validators=[core.validators.validate_logo]),
        ),
    ]
