# Generated by Django 6.0.7 on 2026-07-12 19:31

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sitesettings_optimized_logo_alter_sitesettings_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='optimized_favicon',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='site/favicon/optimized/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Upload a square PNG, JPEG, or WebP image between 192 × 192 and 2048 × 2048 pixels. A 192 × 192 PNG favicon will be created automatically.', null=True, upload_to='site/favicon/originals/', validators=[core.validators.validate_favicon]),
        ),
    ]
