# Generated by Django 6.0.7 on 2026-07-12 19:54

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sitesettings_optimized_favicon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='optimized_social_image',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='site/seo/optimized/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='social_image',
            field=models.ImageField(blank=True, help_text='Upload a PNG, JPEG, or WebP image at least 1200 × 630 pixels and no larger than 5 MB. It will be cropped and optimized to exactly 1200 × 630 pixels.', null=True, upload_to='site/seo/originals/', validators=[core.validators.validate_social_image]),
        ),
    ]
