# Generated by Django 6.0.7 on 2026-07-15 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_companystats'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Site Settings', 'verbose_name_plural': 'Site Settings'},
        ),
    ]
