# Generated by Django 6.0.7 on 2026-08-09 06:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_sitesettings_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='companystats',
            name='singleton_key',
            field=models.PositiveSmallIntegerField(default=1, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='singleton_key',
            field=models.PositiveSmallIntegerField(default=1, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='companystats',
            name='client_satisfaction',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddConstraint(
            model_name='businesshours',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('closing_time__isnull', True), ('is_closed', True), ('opening_time__isnull', True)), models.Q(('closing_time__gt', models.F('opening_time')), ('closing_time__isnull', False), ('is_closed', False), ('opening_time__isnull', False)), _connector='OR'), name='business_hours_times_match_status'),
        ),
        migrations.AddConstraint(
            model_name='companystats',
            constraint=models.CheckConstraint(condition=models.Q(('singleton_key', 1)), name='company_stats_singleton_key_is_one'),
        ),
        migrations.AddConstraint(
            model_name='companystats',
            constraint=models.CheckConstraint(condition=models.Q(('client_satisfaction__gte', 0), ('client_satisfaction__lte', 100)), name='client_satisfaction_between_0_and_100'),
        ),
        migrations.AddConstraint(
            model_name='sitesettings',
            constraint=models.CheckConstraint(condition=models.Q(('singleton_key', 1)), name='site_settings_singleton_key_is_one'),
        ),
    ]
